sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9\\.]+/"
cache:
- composer
- "$HOME/.composer/cache"
php:
- 5.6
- 7.0
env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=nightly WP_MULTISITE=0
before_script:
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- composer install
script:
- composer test
before_deploy:
- echo 'Making deploy packages...'
- rm -rfv .git
- rm -rfv bin
- rm -rfv tests
- rm -rfv .gitignore
- rm -rfv .travis.yml
- rm -rfv vendor
- rm -rfv composer.lock
- rm -rfv phpunit.xml.dist
- zip -r toc-generator.zip ./
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Ba/PPrAbO6G+CcvfrlYvulbNcLeyyt8OzWVAt0v0nJILbbhuRXlvUFopQVtavkX7PtDdU9DLrAOal0Sutu83ZtxiMpHJyPiVuI9wagyrc5ymr6/v4Pir2pDQbl+k0pl8ES9Q7ELqoL34ETw/VfeJpgtajKX1v3vj2ix7ARMRnAcwvHHNq5arX3qjCjXm4DoaPTA38znnCLPN2GJx3hGZ5rUISk1e0+ShEPV4SNH2X2qSCkspZWo78wQmAet2cS8j09Ad0/7w5AGE3hvJPQ3PfCZgUweORcZghmDSaEboJ70TDDds2+qZ8tvaLSD7vUfFP70PJUC3i9xn/kvo2fk8bNg5EMdwM8PmpnAPjpfFau8KUaoOO1Y8KxC0YGevfkMuui5tAjp5zLH6899vpWarYul01FY4HIQGUW8WNZyJQieff9R9xFE4HBo9ez173Hv/1r29BFnahyJQDn8XzyTspT1t9Vk6ubss+dmAU2YCGCkC6LF94l7xUCUc/0DSRFWd9aYdUG+zbZlNXUWqRYLU7XHMCKemK0MjkRVCD3S8NvqRvoOyfQJiGIFtesZLUhnK6NWI/dAXzyQmzXhEhkZafV3sNKbGdWbtaRkm8utkaALd1ohLmpgzPaH1kbMuy3BUFJJ3pMgJEzFK/jyK+EH6C5yadpeMqZZcxKmXVqLJGxU=
  file: toc-generator.zip
  on:
    tags: true
    repo: kuno1/toc-generator
    php: 5.6
