name: Library CI/CD

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        php: [ '7.4', '8.0' ] # PHP versions to check.
        wp: [ 'latest', '5.9' ]      # WordPress version to check.
    uses: tarosky/workflows/.github/workflows/wp-unit-test.yml@main
    with:
      php_version: ${{ matrix.php }}
      wp_version: ${{ matrix.wp }}

  phpcs:
    name: PHP Syntax check
    uses: tarosky/workflows/.github/workflows/phpcs.yml@main
    with:
      version: 7.4

  status-check:
    name: Status Check
    needs: [ test, phpcs ]
    runs-on: ubuntu-latest
    steps:
      - name: Display Status
        run: echo "All Green!"
